#!/bin/bash

if [ $# -ne 1 ]
    then
        echo -e "USAGE: $0 [ command ] \n      command: the command running on the remote host. \n"
    exit 0
fi

for i in `cat /tmp/mgr/online.ip`; do echo "Processing host [ `ssh root@$i 'hostname'` ] ... "; ssh root@$i "$1"; done
